export default [
  'Astronaut',
  'Baker',
  'Blacksmith',
  'Boat Captain',
  'Cartographer',
  'Chef',
  'Clown',
  'Composer',
  'Computer Programmer',
  'Conductor',
  'Construction Worker',
  'Dancer',
  'Data Scientist',
  'Detective',
  'Dog Trainer',
  'Doctor',
  'Electrician',
  'Engineer',
  'Event Planner',
  'Farmer',
  'Fashion Designer',
  'Film Director',
  'Firefighter',
  'Fisherman',
  'Florist',
  'Game Developer',
  'Gardener',
  'Graphic Designer',
  'Hairdresser',
  'Historian',
  'Hotel Manager',
  'Illustrator',
  'Interior Designer',
  'Inventor',
  'Journalist',
  'Judge',
  'Lifeguard',
  'Magician',
  'Marine Biologist',
  'Mathematician',
  'Mechanic',
  'Meteorologist',
  'Music Producer',
  'Musician',
  'Nurse',
  'Nutritionist',
  'Optician',
  'Painter',
  'Paramedic',
  'Park Ranger',
  'Pastry Chef',
  'Personal Trainer',
  'Pharmacist',
  'Photographer',
  'Pilot',
  'Pirate',
  'Plumber',
  'Police Officer',
  'Politician',
  'Professor',
  'Psychologist',
  'Race Car Driver',
  'Radiologist',
  'Real Estate Agent',
  'Receptionist',
  'Robot Designer',
  'Rocket Scientist',
  'Sailor',
  'Sculptor',
  'Secret Agent',
  'Security Guard',
  'Shark Trainer',
  'Shipwright',
  'Singer',
  'Software Engineer',
  'Soldier',
  'Sound Engineer',
  'Speech Therapist',
  'Spy',
  'Statistician',
  'Stunt Performer',
  'Surgeon',
  'Tailor',
  'Tattoo Artist',
  'Teacher',
  'Tour Guide',
  'Translator',
  'Travel Blogger',
  'Treasure Hunter',
  'TV Show Host',
  'Uber Driver',
  'Vegan Chef',
  'Veterinarian',
  'Video Game Tester',
  'Voice Actor',
  'Volcanologist',
  'Waiter',
  'Web Developer',
  'Wedding Planner',
  'Wildlife Photographer',
  'Wine Taster',
  'Zookeeper',
  'Architect',
  'Art Director',
  'Archaeologist',
  'Acrobat',
  'Animal Trainer',
  'Antique Dealer',
  'App Developer',
  'Arms Dealer',
  'Artificial Intelligence Specialist',
  'Astronomer',
  'Ballet Dancer',
  'Bartender',
  'Bee Keeper',
  'Bounty Hunter',
  'Bowling Instructor',
  'Butcher',
  'Caddy',
  'Cameraman',
  'Chauffeur',
  'Circus Performer',
  'Cryptozoologist',
  'DJ',
  'Demolition Expert',
  'Drone Operator',
  'Escape Room Designer',
  'Espresso Consultant',
  'Evil Genius',
  'Falconer',
  'Fiction Writer',
  'Fortune Teller',
  'Fragrance Developer',
  'Freelance Photographer',
  'Frog Whisperer',
  'Futurist',
  'Galactic Trader',
  'Ghost Hunter',
  'Gin Distiller',
  'Goldsmith',
  'Golf Instructor',
  'Guitar Maker',
  'Hacker',
  'Henchman',
  'Herbalist',
  'Highway Patrol Officer',
  'Horror Movie Actor',
  'Ice Cream Taster',
  'Ice Sculptor',
  'Impressionist Painter',
  'Jetpack Instructor',
  'Juggler',
  'Karaoke Host',
  'Knight',
  'Kombucha Brewer',
  'Lab Technician',
  'Laser Tag Referee',
  'Librarian',
  'Luxury Watchmaker',
  'Makeup Artist',
  'Mammoth Handler',
  'Martial Arts Instructor',
  'Massage Therapist',
  'Maze Designer',
  'Medieval Blacksmith',
  'Mentalist',
  'Mime Artist',
  'Mixologist',
  'Model',
  'Movie Critic',
  'Mummy Resurrector',
  'Nanny',
  'Nightclub Promoter',
  'Ninja',
  'Orchestra Conductor',
  'Origami Master',
  'Ostrich Jockey',
  'Paintball Referee',
  'Paleo Diet Specialist',
  'Palm Reader',
  'Paranormal Investigator',
  'Perfume Tester',
  'Pet Psychic',
  'Pizza Chef',
  'Poet',
  'Private Detective',
  'Puppet Maker',
  'Puzzle Designer',
  'Quidditch Coach',
  'Quiz Show Host',
  'Radio DJ',
  'Railway Conductor',
  'Rainforest Guide',
  'Reality Show Contestant',
  'Remote Control Submarine Pilot',
  'Rodeo Clown',
  'Roller Coaster Designer',
  'Rum Distiller',
  'Safari Guide',
  'Sailmaker',
  'Samurai',
  'Santa Claus',
  'Saxophonist',
  'Science Fiction Writer',
  'Screenwriter',
  'Sea Captain',
  'Seismologist',
  'Serpent Trainer',
  'Sherpa',
  'Silversmith',
  'Skeleton Racer',
  'Skydiving Instructor',
  'Soap Opera Star',
  'Social Media Influencer',
  'Sommelier',
  'Space Pirate',
  'Speech Writer',
  'Steeplejack',
  'Stonemason',
  'Surfing Instructor',
  'Sword Swallower',
  'Symphony Conductor',
  'Tarantula Breeder',
  'Taxidermist',
  'Thief',
  'Toy Designer',
  'Trebuchet Engineer',
  'Tree Surgeon',
  'Trivia Host',
  'Tugboat Captain',
  'Ventriloquist',
  'Violin Maker',
  'Vlogger',
  'Wand Maker',
  'War Correspondent',
  'Water Slide Tester',
  'Weatherman',
  'Wedding DJ',
  'Whale Song Analyst',
  'Wheel of Fortune Contestant',
  'Wind Turbine Technician',
  'Wine Critic',
  'Witch Doctor',
  'World Record Holder',
  'Yacht Designer',
  'Yeti Tracker',
  'Yo-Yo Champion',
  'Yoga Instructor',
  'Zombie Apocalypse Survivalist',
];
