export default [
  'Astronaut',
  'Baker',
  'Chef',
  'Computer Programmer',
  'Construction Worker',
  'Dancer',
  'Data Scientist',
  'Detective',
  'Dog Trainer',
  'Doctor',
  'Electrician',
  'Engineer',
  'Event Planner',
  'Farmer',
  'Fashion Designer',
  'Film Director',
  'Firefighter',
  'Florist',
  'Game Developer',
  'Gardener',
  'Graphic Designer',
  'Hairdresser',
  'Historian',
  'Hotel Manager',
  'Interior Designer',
  'Journalist',
  'Judge',
  'Lifeguard',
  'Magician',
  'Mathematician',
  'Mechanic',
  'Musician',
  'Nurse',
  'Nutritionist',
  'Optician',
  'Painter',
  'Personal Trainer',
  'Pharmacist',
  'Photographer',
  'Pilot',
  'Plumber',
  'Police Officer',
  'Politician',
  'Professor',
  'Psychologist',
  'Real Estate Agent',
  'Receptionist',
  'Rocket Scientist',
  'Secret Agent',
  'Security Guard',
  'Singer',
  'Software Engineer',
  'Soldier',
  'Spy',
  'Surgeon',
  'Tailor',
  'Tattoo Artist',
  'Teacher',
  'Travel Blogger',
  'TV Show Host',
  'Uber Driver',
  'Video Game Tester',
  'Voice Actor',
  'Waiter',
  'Web Developer',
  'Wedding Planner',
  'Wildlife Photographer',
  'Wine Taster',
  'Architect',
  'Archaeologist',
  'Animal Trainer',
  'Antique Dealer',
  'App Developer',
  'Arms Dealer',
  'Artificial Intelligence Specialist',
  'Astronomer',
  'Ballet Dancer',
  'Bartender',
  'Bee Keeper',
  'Bowling Instructor',
  'Caddy',
  'Cameraman',
  'Chauffeur',
  'DJ',
  'Drone Operator',
  'Fiction Writer',
  'Fortune Teller',
  'Fragrance Developer',
  'Freelance Photographer',
  'Ghost Hunter',
  'Goldsmith',
  'Golf Instructor',
  'Guitar Maker',
  'Hacker',
  'Highway Patrol Officer',
  'Horror Movie Actor',
  'Ice Cream Taster',
  'Ice Sculptor',
  'Juggler',
  'Karaoke Host',
  'Lab Technician',
  'Laser Tag Referee',
  'Librarian',
  'Luxury Watchmaker',
  'Makeup Artist',
  'Martial Arts Instructor',
  'Massage Therapist',
  'Model',
  'Movie Critic',
  'Nanny',
  'Nightclub Promoter',
  'Ninja',
  'Palm Reader',
  'Paranormal Investigator',
  'Perfume Tester',
  'Pizza Chef',
  'Poet',
  'Quiz Show Host',
  'Radio DJ',
  'Railway Conductor',
  'Reality Show Contestant',
  'Roller Coaster Designer',
  'Rum Distiller',
  'Safari Guide',
  'Samurai',
  'Santa Claus',
  'Saxophonist',
  'Science Fiction Writer',
  'Screenwriter',
  'Skydiving Instructor',
  'Social Media Influencer',
  'Speech Writer',
  'Surfing Instructor',
  'Thief',
  'Toy Designer',
  'Vlogger',
  'Water Slide Tester',
  'Weatherman',
  'Wedding DJ',
  'Wine Critic',
  'World Record Holder',
  'Yo-Yo Champion',
  'Yoga Instructor',
];
