export default [
  'Juggling Flaming Torches',
  'Mastering the Art of Sandwich Making',
  'Speaking Fluent Whale',
  'Extreme Ironing',
  'Underwater Basket Weaving',
  'Competitive Dog Grooming',
  'Speed Origami',
  'Morse Code Tap Dancing',
  'Balloon Animal Sculpting',
  'Expert Tea Tasting',
  'Skywriting with Kites',
  'Ping Pong Ball Balancing',
  'Speed Reading Comic Books',
  'Advanced Rock-Paper-Scissors Strategy',
  'Knitting with Spaghetti',
  'Synchronized Swimming Solo',
  'Unicycle Jousting',
  'Glow Stick Twirling',
  'Advanced Cheese Rolling',
  'Pen Spinning',
  'Freestyle Rap About Vegetables',
  'Spelling Bee Ventriloquism',
  'Human Beatboxing',
  'Mastering Tongue Twisters',
  'Speed Gardening',
  'Dinosaur Call Mimicry',
  'Fort Building',
  'Snow Sculpture Carving',
  'Extreme Sudoku',
  'Soap Carving',
  'Umbrella Spinning',
  'Improvisational Haiku Writing',
  'Kite Surfing',
  'Paper Airplane Folding',
  'Pantomime',
  'Speed Puzzle Solving',
  'Guitar Playing with Feet',
  'Shadow Puppetry',
  'Writing Backwards',
  'Whistling Opera Tunes',
  'Rubber Chicken Juggling',
  'Whittling Soap Bars',
  'Extreme Hula Hooping',
  'Jelly Bean Sorting',
  'Miming Invisible Walls',
  'Whispering Secrets to Trees',
  'Underwater Running',
  'Jump Rope with Invisible Rope',
  'Dodgeball Dodging',
  'Spoon Bending with Mind',
  'Singing in Whale Song',
  'Lip Syncing to Elevator Music',
  'Stilts Walking',
  'Invisible Car Driving',
  'Speed Pole Vaulting',
  'Instant Portrait Drawing',
  'Magic Tricks with Cards',
  'Eyelid Flipping',
  'Speed Hammock Hanging',
  'Silent Movie Acting',
  'Sandcastle Architect',
  'Origami Folding with One Hand',
  'Speed Pottery',
  'Bottle Flipping',
  'Extreme Macramé',
  'Cloud Watching',
  'Instant Mashed Potato Sculpting',
  'Soap Bubble Sculpting',
  'Rainbow Catching',
  'Lightning Speed Typing',
  'Pin the Tail on the Donkey Champion',
  'Jumping Rope Backwards',
  'Fast Forward Movie Watching',
  'Predicting Coin Toss Outcomes',
  'Echo Location Navigation',
  'Potato Peeling',
  'Balancing on One Leg',
  'Super Fast Hand Clapping',
  'Pinball Wizardry',
  'Human Pretzel Contortion',
  'Name That Tune',
  'One Breath Whistling',
  'Speed Hair Braiding',
  'Fastest Hotdog Eating',
  'Spinning Plates on Sticks',
  'Building House of Cards',
  'Origami Napkin Folding',
  'Beard Growing',
  'Breakdancing with Books',
  'Reading Aloud in Slow Motion',
  'Card Tower Building',
  'Rolling Your Tongue',
  'Painting with Toes',
  'Balancing Books on Head',
  'Freestyle Knitting',
  'Blinking Morse Code',
  'Extreme Ice Cream Scooping',
  'Invisible Sword Fencing',
  'Breathing Through One Nostril',
  'Fastest Ice Melting',
  'Speedy Book Summarizing',
  'Upside-Down Reading',
  'Advanced Hide and Seek',
  'Silent Disco Dancing',
  'Whistle Tunes with Nose',
  'Speedy Broom Sweeping',
  'Echo Mimicry',
  'Drawing Without Looking',
  'Balancing Spinning Plates',
  'Bubble Wrap Popping',
  'Lightning Speed Shoe Tying',
  'High-Speed Paper Cutting',
  'Speedy Hair Curling',
  'Fast Handwriting',
  'Super Fast Eye Blinking',
  'Paper Cup Pyramid Building',
  'Instant Tattoo Design',
  'Synchronized Solo Dance',
  'Balancing on Two Fingers',
  'Finger Knitting',
  'Whistle Symphony',
  'Super Fast Shoe Polishing',
  'Advanced Tic-Tac-Toe Strategy',
  'Jump Rope Double Dutch',
  'Fortune Cookie Writing',
  'Fast-Food Wrapping',
  'Air Guitar Master',
  'One-Handed Typing',
  'Speed Eating Spaghetti',
  'Imitating Cat Purring',
  'Ventriloquism Without Dummy',
  'Silent Opera Singing',
  'Speedy Nail Painting',
  'Snap Finger Clicking',
  'Whistling While Walking',
  'Speed Paper Tearing',
  'Napkin Folding Art',
  'Finger Puppetry',
  'Spin a Basketball on a Finger',
  'Knot Tying',
  'Tea Brewing Mastery',
  'Human Statue Imitation',
  'Extreme Finger Snapping',
  'Sandwich Sculpting',
  'Silent Scream',
  'Doodle Art',
  'High-Speed Cookie Cutting',
  'Double Jointed Tricks',
  'Jumping in Place',
  'Thumb Wrestling',
  'Talking Like a Robot',
  'Incredible Sleeping Skills',
  'Fast-Talking',
  'Speed Painting',
  'Backwards Walking',
  'Super Fast Apple Peeling',
  'Flipping Pancakes in the Air',
  'Standing on Your Head',
  'Running in Place',
  'Pencil Twirling',
  'Rapid Fire Jokes',
  'Singing in the Shower',
  'Skateboarding',
  'Building Sandcastles',
  'Extreme Yoga Poses',
  'Jumping Jack Mastery',
  'Speed Lego Building',
  'Drawing Cartoons',
  'Invisible Ink Writing',
  'Fast Skipping',
  'Super Fast Puzzle Assembly',
  'Bouncing a Ball Continuously',
  'Walking a Tightrope',
  'Spinning in Circles',
  'Tightrope Walking',
  'Speed Sudoku Solving',
  'Building Towers from Toothpicks',
  'Finger Painting',
  'Dancing Like a Robot',
  'Bubble Blowing',
  'Skip Counting',
  'Silent Reading Out Loud',
  'Drawing in the Air',
  'Flipping Through Books',
  'Balancing a Pencil on Your Nose',
  'Pen Spinning Tricks',
  'Hopping on One Foot',
  'Speed Typing with Eyes Closed',
  'Skipping Rocks on Water',
  'Bounce a Basketball with Your Head',
  "Rolling Your R's",
  'Building Model Airplanes',
  'Speed Weaving',
  'Speed Cake Decorating',
  'Fast Shoe Lacing',
  'Balancing a Broom on Your Chin',
  'Advanced Snowball Fighting',
  'Speed Flossing (Teeth)',
  'Swing Dancing',
  'Fast Fruit Peeling',
  'Chopstick Mastery',
  'Speed Sweeping',
  'Ninja Stealth',
  'Rapping',
  'Belly Dancing',
  'Speed Storytelling',
  'Playing Air Drums',
  'Building with Wooden Blocks',
  'Cartwheel Mastery',
  'Balancing on a Unicycle',
  'Speed Typing',
  'Super Fast Finger Snapping',
  'High-Speed Paper Airplane Folding',
  'Climbing Trees',
  'Super Fast Doodling',
  'Drawing Comic Strips',
  'Building Domino Runs',
  'Playing Hopscotch',
  'Jumping Over Obstacles',
  'Rolling Down Hills',
  'Skipping Rope',
  'Fast and Furious Knitting',
  'Speed Hair Braiding',
  'Balancing on a Single Finger',
  'Whistling to a Melody',
  'Super Fast Typing',
  'Speed Puzzle Solving',
  'Balancing a Spoon on Your Nose',
  'Jumping High in the Air',
  'Flip Cup Champion',
  'Advanced Soap Carving',
  'Balancing a Pencil on Your Finger',
  'Skipping Stones on a Lake',
  'Super Fast Rope Climbing',
  'Advanced Dodgeball Dodging',
  'Walking on Stilts',
  'Jumping Over Shadows',
  'Invisible Ink Writing',
  'Extreme Jump Rope',
  'Super Fast Candy Wrapping',
  'Super Fast Drawing',
  'Building Card Houses',
  'Silent Whistling',
  'One Handed Clapping',
  'Fast Fruit Carving',
  'Walking on Your Hands',
  'Speed Rolling Dough',
  'Spinning a Top',
  'Super Fast Reading',
  'Super Fast Cleaning',
  'Building Block Castles',
  'Speed Typing Without Looking',
  'Whispering Loudly',
  'Running Super Fast',
  'Super Fast Knitting',
  'Speed Balancing on One Foot',
  'Skipping Rope Double Time',
  'Jumping Jacks at Lightning Speed',
  'Building Lego Structures',
  'Super Fast Shoe Tying',
  'Drawing with Eyes Closed',
  'Extreme Cup Stacking',
  'Skipping Rope Backwards',
  'Speed Handwriting',
  'Jumping Super High',
  'Extreme Hide and Seek',
  'Building Domino Towers',
  'Drawing Fast Portraits',
  'Super Fast Walking',
  'Juggling Three Balls',
  'Fast Puzzle Solving',
  'Building Towers from Cards',
  'Flipping Pancakes Super Fast',
  'Jumping on a Trampoline',
  'Building a House of Cards',
  'Moonwalking on Ice',
  'Viking Beard Braiding',
  'Speed Snowman Building',
  'Gourmet Pizza Topping Arrangement',
  'Shadow Art Mastery',
  'Backwards Bike Riding',
  'Origami with Giant Paper',
  'Balloon Animal Sculpting',
  'Underwater Basket Weaving',
  'Extreme Cupcake Decorating',
  'Glow-in-the-Dark Face Painting',
  'Cartwheel while Juggling',
  'Advanced Sandcastle Engineering',
  'Marathon Bubble Blowing',
  'Instant Poetry Writing',
  'Telekinetic Paper Folding',
  'Pumpkin Carving Champion',
  'Speed Scrapbooking',
  'Finger Shadow Puppetry',
  'Blindfolded Speed Typing',
  'Toothpick Bridge Building',
  'Sneaker Customization',
  'Freestyle Haiku Composition',
  'Epic Snowball Fight Tactics',
  'Finger Painting Masterpieces',
  "Gourmet S'mores Creation",
  'Speed Lego Tower Construction',
  'Upside-Down Drawing',
  'One-Handed Typing',
  'Glow Stick Dancing',
  'Competitive Kite Flying',
  'Walking a Tightrope',
  'Multilingual Tongue Twisters',
  'Speed Ice Cream Sundae Making',
  'Fastest Paper Airplane Folding',
  'Synchronizing Wristwatch Collection',
  'Building Card Towers',
  'Perfect Pancake Flipping',
  'Spinning Plates on Poles',
  'Advanced Yo-Yo Tricks',
  'Marshmallow Sculpting',
  'Super Soaker Strategy',
  'Rainbow Cake Layering',
  'Expert Chocolate Tasting',
  'Space-Themed Room Decoration',
  'Speed Sock Puppet Creation',
  'Rapid Fire Trivia Answering',
  'Incredible Blanket Fort Building',
  'Walking Backwards with Style',
  'DIY Comic Book Creation',
  'Elaborate Moustache Styling',
  'Animal Balloon Origami',
  'Upside-Down Handwriting',
  'Chalkboard Art',
  'Hyper Speed Jigsaw Puzzle Solving',
  'Secret Handshake Design',
  'High-Speed Board Game Playing',
  'Invisible Ink Writing',
  "Fastest Rubik's Cube Solving",
  'Soap Bubble Sculpting',
  'Speed Beard Trimming',
  'Creative Pancake Art',
  'Extreme Hula Hooping',
  'Epic Dance-Off Moves',
  'Fastest Fortune Cookie Writing',
  'DIY Puzzle Creation',
  'Mind-Blowing Card Tricks',
  'Personalized Gift Wrapping',
  'Speed Origami with Dollar Bills',
  'Lollipop Bouquet Making',
  'Underwater Scavenger Hunt Mastery',
  'Custom Emoji Design',
  'Speed Cup Stacking',
  'Hyper Realistic Face Painting',
  'Elaborate Sandwich Making',
  'Extreme Snow Angel Creation',
  'Epic Pillow Fort Design',
  'Record-Breaking Domino Setup',
  'Creative Snowflake Cutting',
  'Double Dutch Jump Rope',
  'Speed Marshmallow Roasting',
  'Super Fast Book Summarizing',
  'Blindfolded Maze Navigation',
  'Unicycle Freestyle',
  'Advanced Puzzle Box Solving',
  'Incredible Impersonations',
  'Cartoon Voice Acting',
  'Superhero Costume Design',
  'Bubblegum Blowing Contests',
  'Speed Chess Playing',
  'Stunning Hand Lettering',
  'Interactive Storytelling',
  'Speed Toy Assembly',
  'Miniature Model Making',
  'Epic Paper Mâché Sculpting',
  'Masterful Pie Crust Designing',
  'Flash Mob Choreography',
  'Backyard Astronomy',
  'Speedy Crossword Puzzle Solving',
  'Hyper Realistic Dollhouse Decoration',
  'Whistle in Harmony',
  'Fortune Telling with Cookies',
  'Fastest Monopoly Game Finishing',
  'Perfect Paper Snowflake Cutting',
  'Extreme Snow Shoveling',
  'Customized Hot Chocolate Creation',
  'Speedy Gingerbread House Building',
  'Paper Cutting Art',
  'Epic Sand Art Masterpieces',
  'Super Fast Cookie Decorating',
  'Speedy Hand Whistling',
  'Spontaneous Puppet Shows',
  'Speedy Treasure Hunt Designing',
  'Advanced Puzzle Strategy',
  'Fastest Christmas Tree Decorating',
  'Creative Hand Shadow Art',
  'Ultimate Pillow Fight Strategy',
  'Glow-in-the-Dark Finger Painting',
  'Rapid Fire Joke Telling',
  'Incredible Slacklining',
  'Speedy Craft Beer Tasting',
  'Underwater Handstands',
  'High-Speed Rap Battles',
  'Extreme DIY Crafting',
  'Masterful Face Mask Design',
  'Superhero Story Writing',
  'Hyper Realistic Model Train Setup',
  'Epic Gingerbread Architecture',
  'Fastest Snowball Rolling',
  'Speed Tree Climbing',
  'Customized Candle Making',
  'Speed Lip Syncing',
  'Glow-in-the-Dark Dancing',
  'Speedy Hand-Knitting',
  'Epic Storybook Writing',
  'High-Speed Sock Matching',
  'Creative Scrapbooking',
  'Ultimate Hide and Seek Strategies',
  'Speedy Garden Maze Solving',
  'Super Fast Pictionary Drawing',
  'Instant Costume Designing',
  'Speedy Hand Clapping',
  'Perfect Gift Wrapping',
  'Speedy Balloon Filling',
  'Lightning Fast T-Shirt Folding',
  'Extreme Maze Building',
  'Lightning Fast Cookie Cutting',
  'Speedy Papercraft',
  'Rapid Fire Sing-Along',
  'Epic Theme Party Planning',
  'Advanced Fortune Cookie Writing',
  'Hyper Speed Nail Painting',
  'Incredible Balloon Sculpting',
  'Fastest Paper Crane Folding',
  'Masterful Chalk Mural Design',
  'Super Fast Gift Unwrapping',
  'Speedy Hand Washing',
  'Rapid Fire Compliment Giving',
  'Speedy Cartoon Sketching',
  'Creative Costume Creation',
  'Speedy DIY Snow Globes',
  'Hyper Realistic Dollhouse Design',
  'Ultimate Campfire Storytelling',
  'Speedy Birdhouse Building',
  'Fastest Rock Collection Sorting',
  'Extreme Frisbee Throwing',
  'Creative Ice Sculpture Design',
  'Speedy Necklace Beading',
  'Super Fast Christmas Wrapping',
  'Speedy Sandcastle Building',
  'Epic Treehouse Design',
  'Lightning Speed Gingerbread House Decorating',
  'Speedy Paper Plate Decorating',
  'Ultimate Snowball Throwing',
  'Rapid Fire Party Game Playing',
  'High-Speed Napkin Folding',
  'Epic Balloon Arch Designing',
  'Speedy DIY Puzzle Solving',
  'Ultimate Backyard BBQ Planning',
  'Hyper Speed Card Playing',
  'Incredible Custom Cookie Design',
  'Super Fast Paper Cutting',
  'Speedy Home Makeover Planning',
  'Epic Sand Dune Surfing',
  'Creative Pottery Making',
  'Speedy Paper Sculpture Crafting',
  'Ultimate Backyard Camping Planning',
  'Speedy Handcrafting',
  'Extreme Yarn Bombing',
  'Lightning Speed DIY Costumes',
  'Speedy Paper Mache Modeling',
  'Ultimate Backyard Water Balloon Fight Strategy',
  'Speedy Friendship Bracelet Making',
  'Hyper Speed Pumpkin Carving',
  'Creative DIY Jewelry Making',
  'Fastest Cupcake Frosting',
  'Super Fast Christmas Tree Decorating',
  'Speedy Hand Puppet Shows',
  'Ultimate Fire Pit Building',
  'Speedy Paper Crafting',
  'Hyper Realistic Pumpkin Painting',
  'Creative Paper Quilling',
  'Speedy Snowman Building',
  'Epic Pillow Design',
  'Ultimate Snowball Fight Strategy',
  'Speedy Paper Flower Making',
  'Super Fast Wall Mural Painting',
  'Creative Chalkboard Art',
  'Speedy Homemade Christmas Ornament Crafting',
  'Hyper Speed Candle Making',
  'Super Fast Pie Crust Pinching',
  'Speedy Sand Castle Engineering',
  'Ultimate Holiday Party Planning',
  'Creative Paper Airplane Design',
  'Speedy Birthday Party Planning',
  'Hyper Speed House of Cards Building',
  'Ultimate Backyard Obstacle Course Design',
  'Speedy DIY Holiday Decorations',
  'Super Fast Scrapbook Assembling',
  'Speedy Papercraft Ornaments',
  'Ultimate Backyard Sports Day Planning',
  'Hyper Realistic Portrait Drawing',
  'Speedy Miniature Model Building',
  'Super Fast Papercraft Creations',
  'Ultimate Glow-in-the-Dark Party Planning',
  'Speedy Holiday Cookie Decorating',
  'Epic Costume Jewelry Making',
  'Hyper Realistic Miniature Sculpting',
  'Super Fast Party Planning',
  'Ultimate Picnic Planning',
  'Speedy Hand-Lettering',
  'Hyper Speed Card Tower Building',
  'Super Fast Model Airplane Building',
  'Ultimate Garden Party Planning',
  'Speedy Calligraphy',
  'Hyper Realistic Model Building',
  'Speedy Holiday Card Making',
  'Ultimate DIY Crafting',
  'Speedy Puzzle Solving',
  'Hyper Speed Holiday Crafting',
  'Super Fast Christmas Decorating',
  'Ultimate Backyard Party Planning',
  'Speedy Custom Cake Decorating',
  'Hyper Realistic Landscape Painting',
  'Super Fast Custom Ornament Making',
  'Ultimate Picnic Basket Packing',
  'Speedy Mosaic Tiling',
  'Hyper Speed Ice Cream Sundae Building',
  'Ultimate Snow Day Planning',
  'Speedy DIY Holiday Gift Making',
  'Hyper Speed Gingerbread House Building',
  'Super Fast Holiday Decorating',
  'Ultimate Backyard Adventure Planning',
  'Speedy DIY Ornament Making',
  'Hyper Realistic Face Painting',
  'Super Fast Holiday Wrapping',
  'Ultimate Birthday Bash Planning',
];
